Create/Update Product endpoint
---
tags:
  - Products
consumes:
  - application/json
parameters:
  - in: body
    name: body
    required: true
    schema:
      type: object
      required:
        - name
        - comment
        - quantity
        - company_id
      properties:
        name:
          type: string
          example: "Keyboard Roccat"
        comment:
          type: string
          example: "Nice keyboard"
        quantity:
          type: integer
          example: 2
        company_id:
          type: integer
          example: 1
definitions:
  Product:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      comment:
        type: string
      quantity:
        type: integer
      company_id:
        type: integer
responses:
  200:
    description: The created/updated product
    schema:
      $ref: '#/definitions/Product'
    examples:
      - {"id": 1, "name": "Keyboard Roccat", "comment": "Nice", "quantity": 2, "company_id": 1}
